export const GET_CONTACT_LIST_PENDING = 'GET_CONTACT_LIST_PENDING';
export const GET_CONTACT_LIST_SUCCESS = 'GET_CONTACT_LIST_SUCCESS';
export const GET_CONTACT_LIST_ERROR = 'GET_CONTACT_LIST_ERROR';
