export const GET_CONTACT_LIST_PENDING = 'GET_CONTACT_LIST_PENDING';
export const GET_CONTACT_LIST_SUCCESS = 'GET_CONTACT_LIST_SUCCESS';
export const GET_CONTACT_LIST_ERROR = 'GET_CONTACT_LIST_ERROR';

export const GET_ALL_CONTACTS_PENDING = 'GET_ALL_CONTACTS_PENDING';
export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_ERROR = 'GET_ALL_CONTACTS_ERROR';
