export const GET_RELATION_LIST_PENDING = 'GET_RELATION_LIST_PENDING';
export const GET_RELATION_LIST_SUCCESS = 'GET_RELATION_LIST_SUCCESS';
export const GET_RELATION_LIST_ERROR = 'GET_RELATION_LIST_ERROR';

export const GET_ALL_RELATIONS_PENDING = 'GET_ALL_RELATIONS_PENDING';
export const GET_ALL_RELATIONS_SUCCESS = 'GET_ALL_RELATIONS_SUCCESS';
export const GET_ALL_RELATIONS_ERROR = 'GET_ALL_RELATIONS_ERROR';
