export const GET_RELATION_LIST_PENDING = 'GET_RELATION_LIST_PENDING';
export const GET_RELATION_LIST_SUCCESS = 'GET_RELATION_LIST_SUCCESS';
export const GET_RELATION_LIST_ERROR = 'GET_RELATION_LIST_ERROR';
