export const GET_NOTE_PENDING = 'GET_NOTE_PENDING';
export const GET_NOTE_SUCCESS = 'GET_NOTE_SUCCESS';
export const GET_NOTE_ERROR = 'GET_NOTE_ERROR';

export const POST_NOTE_PENDING = 'POST_NOTE_PENDING';
export const POST_NOTE_SUCCESS = 'POST_NOTE_SUCCESS';
export const POST_NOTE_ERROR = 'POST_NOTE_ERROR';

export const PUT_NOTE_PENDING = 'PUT_NOTE_PENDING';
export const PUT_NOTE_SUCCESS = 'PUT_NOTE_SUCCESS';
export const PUT_NOTE_ERROR = 'PUT_NOTE_ERROR';

export const DELETE_NOTE_PENDING = 'DELETE_NOTE_PENDING';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR';
