export const GET_CONTACT_PENDING = 'GET_CONTACT_PENDING';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_ERROR = 'GET_CONTACT_ERROR';

export const POST_CONTACT_PENDING = 'POST_CONTACT_PENDING';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_CONTACT_ERROR = 'POST_CONTACT_ERROR';

export const PUT_CONTACT_PENDING = 'PUT_CONTACT_PENDING';
export const PUT_CONTACT_SUCCESS = 'PUT_CONTACT_SUCCESS';
export const PUT_CONTACT_ERROR = 'PUT_CONTACT_ERROR';

export const DELETE_CONTACT_PENDING = 'DELETE_CONTACT_PENDING';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';
