export const ADD_CONTACTS_PENDING = 'ADD_CONTACTS_PENDING';
export const ADD_CONTACTS_SUCCESS = 'ADD_CONTACTS_SUCCESS';
export const ADD_CONTACTS_ERROR = 'ADD_CONTACTS_ERROR';

export const INITIALIZE_DB_PENDING = 'INITIALIZE_DB_PENDING';
export const INITIALIZE_DB_SUCCESS = 'INITIALIZE_DB_SUCCESS';
export const INITIALIZE_DB_ERROR = 'INITIALIZE_DB_ERROR';
