export const GET_NOTE_LIST_PENDING = 'GET_NOTE_LIST_PENDING';
export const GET_NOTE_LIST_SUCCESS = 'GET_NOTE_LIST_SUCCESS';
export const GET_NOTE_LIST_ERROR = 'GET_NOTE_LIST_ERROR';

export const GET_ALL_NOTES_PENDING = 'GET_ALL_NOTES_PENDING';
export const GET_ALL_NOTES_SUCCESS = 'GET_ALL_NOTES_SUCCESS';
export const GET_ALL_NOTES_ERROR = 'GET_ALL_NOTES_ERROR';
