export const GET_EVENT_LIST_PENDING = 'GET_EVENT_LIST_PENDING';
export const GET_EVENT_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';
export const GET_EVENT_LIST_ERROR = 'GET_EVENT_LIST_ERROR';

export const GET_ALL_EVENTS_PENDING = 'GET_ALL_EVENTS_PENDING';
export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
export const GET_ALL_EVENTS_ERROR = 'GET_ALL_EVENTS_ERROR';
