export const POST_RELATION_PENDING = 'POST_RELATION_PENDING';
export const POST_RELATION_SUCCESS = 'POST_RELATION_SUCCESS';
export const POST_RELATION_ERROR = 'POST_RELATION_ERROR';

export const PUT_RELATION_PENDING = 'PUT_RELATION_PENDING';
export const PUT_RELATION_SUCCESS = 'PUT_RELATION_SUCCESS';
export const PUT_RELATION_ERROR = 'PUT_RELATION_ERROR';

export const DELETE_RELATION_PENDING = 'DELETE_RELATION_PENDING';
export const DELETE_RELATION_SUCCESS = 'DELETE_RELATION_SUCCESS';
export const DELETE_RELATION_ERROR = 'DELETE_RELATION_ERROR';
