export const GET_EVENT_PENDING = 'GET_EVENT_PENDING';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';

export const POST_EVENT_PENDING = 'POST_EVENT_PENDING';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_ERROR = 'POST_EVENT_ERROR';

export const PUT_EVENT_PENDING = 'PUT_EVENT_PENDING';
export const PUT_EVENT_SUCCESS = 'PUT_EVENT_SUCCESS';
export const PUT_EVENT_ERROR = 'PUT_EVENT_ERROR';

export const DELETE_EVENT_PENDING = 'DELETE_EVENT_PENDING';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';
